database:
  url: "sqlite:///:memory:"
  pool_size: 5
  max_overflow: 10

redis:
  url: "redis://localhost:6379"
  db: 1

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchange: "gridbot_test"

binance:
  testnet: true
  timeout: 10000

telegram:
  bot_token: "test_token"
  chat_id: "test_chat_id"

# The actual key will be set via environment variable in conftest.py
encryption_key: ""

trading:
  default_leverage: 2
  max_active_bots_per_client: 2
  min_grid_spacing: 0.01 